name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
      - name: Python version
        run: python -V
      - name: Install deps
        run: pip install -r dev-requirements.txt
      - name: Run tests
        run: pytest tests
