name: CI
on: [push, pull_request]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
      - name: Run pre-commit hook
        uses: pre-commit/action@v3.0.0
